CREATE DATABASE FlowerShop;

--USE FlowerShop;

CREATE TABLE TAIKHOAN
(
	TaiKhoan VARCHAR(20) PRIMARY KEY NOT NULL,
	MatKhau NVARCHAR(10) NOT NULL,
	NgayLapTK DATE NOT NULL,
	TrangThai BIT DEFAULT 1 NOT NULL,
	--1: đã kích họa tài khoản
	--0: chưa kích họa
	LoaiTK CHAR(2) NOT NULL
    --NS: nhân sự
    --QT: quản trị
    --QL: quản lí
    --KH: khách hàng
);

CREATE TABLE NHANVIEN
(
	MaNV CHAR(5) PRIMARY KEY,
	TaiKhoan VARCHAR(20) NOT NULL,
	HoTenNV NVARCHAR(50) NOT NULL,
	DiaChiNV TEXT NOT NULL,
	NgaySinhNV DATE,
	EmailNV NVARCHAR(30) NOT NULL,
	SDT_NV VARCHAR(10) NOT NULL,
	LoaiNV CHAR(2) NOT NULL,
    --QL: quản lí
    --NS: nhân sự
    --BH: bán hàng
    --QT: quản trị
	FOREIGN KEY (TaiKhoan) REFERENCES TaiKhoan(TaiKhoan)
);

CREATE TABLE KHACHHANG
(
	MaKH CHAR(10) PRIMARY KEY,
	TaiKhoan VARCHAR(20) NOT NULL,
	HoTenKH NVARCHAR(50) NOT NULL,
	DiaChiKH NTEXT NOT NULL,
	SDT VARCHAR(10) NOT NULL,
	EmailKH VARCHAR(50) NOT NULL,
	DiemTichLuy INT DEFAULT 0 CONSTRAINT TaiKhoanKH_DiemTichLuy CHECK (DiemTichLuy >=0),
	SoTienDaDung MONEY NOT NULL DEFAULT 0 CONSTRAINT TaiKhoanKH_SoTienDaDung CHECK (SoTienDaDung >=0),
	FOREIGN KEY (TaiKhoan) REFERENCES TaiKhoan(TaiKhoan)
);

CREATE TABLE LUONG
(
	MaNV CHAR(5) NOT NULL,
	NgayNhanLuong DATE DEFAULT GETDATE() NOT NULL,
	LuongCung DECIMAL(15, 2) NOT NULL,
	LuongThuong DECIMAL(15, 2) DEFAULT 0 NOT NULL,
	PRIMARY KEY (MaNV, NgayNhanLuong),
	FOREIGN KEY (MaNV) REFERENCES NHANVIEN (MaNV)
);

CREATE TABLE DIEMDANH
(
	MaCa INT NOT NULL,
	MaNV CHAR(5) NOT NULL,
    NgayDiLam Date NOT NULL,
	PRIMARY KEY (MaCa, MaNV),
	FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
);

CREATE TABLE NHACUNGCAP 
(
	MaNCC CHAR(5) PRIMARY KEY,
	TenNCC NVARCHAR(30) NOT NULL,
	DiaChiNCC NTEXT NOT NULL,
	SDTNCC VARCHAR(10) NOT NULL,
	EmailNCC VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE SANPHAM 
(
	MaSP CHAR(5) PRIMARY KEY,
	TenSP NVARCHAR(50) NOT NULL,
	MoTaSP NTEXT NOT NULL DEFAULT '',
	SoLuongTonKho INT DEFAULT 0 CONSTRAINT SoLuongTonKho CHECK (SoLuongTonKho >= 0),
	LoaiSP NVARCHAR(30) NOT NULL,
	GiaSP MONEY NOT NULL CONSTRAINT SP_GiaSP CHECK (GiaSP >= 0),
);

CREATE TABLE LICH_SU_GIA 
(
	MaSP CHAR(5) NOT NULL,
	NgayCapNhat DATE NOT NULL,
	GiaCapNhat MONEY  NOT NULL CONSTRAINT ThayDoiGia CHECK (GiaCapNhat >= 0),
	PRIMARY KEY (MaSP, NgayCapNhat),
	FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)
);

CREATE TABLE HOADON
(
    MaHD CHAR(10) PRIMARY KEY,
	MaKH CHAR(10) NOT NULL,
    DiaChiGiaoHang NTEXT NOT NULL,
    HinhThucThanhToan NVARCHAR(5),       --ATM       --COD (Cash On Delivery)
    NgayLapHD DATE NOT NULL DEFAULT GETDATE(),
    MaNV CHAR(5),
	TongHD MONEY NOT NULL CONSTRAINT TongGiaHD CHECK (TongHD > 0),
	FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
	FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH)
);

CREATE TABLE CT_HOADON
(
    MaHD CHAR(10) NOT NULL,
    MaSP CHAR(5) NOT NULL,
    DonGiaHD MONEY NOT NULL CONSTRAINT CTHD_DonGia CHECK (DonGiaHD >= 0),
    GiaGiamHD MONEY DEFAULT 0 CONSTRAINT CTHD_GiaGiam CHECK (GiaGiamHD >= 0),
    SoLuongSP INT NOT NULL CONSTRAINT CTHD_SoLuong CHECK (SoLuongSP > 0),
    PRIMARY KEY (MaHD,MaSP),
	FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD),
	FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)
);

CREATE TABLE DONNHAPHANG
(
    MaDNH INT PRIMARY KEY IDENTITY(1,1),
    NgayLapDNH DATE NOT NULL DEFAULT GETDATE(),
    MaNV CHAR(5) NOT NULL,
	MaNCC CHAR(5) NOT NULL,
	TongGiaDNH MONEY NOT NULL CONSTRAINT TongGiaDNH CHECK (TongGiaDNH >= 0),
	FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
	FOREIGN KEY (MaNCC) REFERENCES NHACUNGCAP(MaNCC)
);

CREATE TABLE CT_DONNHAPHANG 
(
    MaDNH INT NOT NULL,
    MaSP CHAR(5) NOT NULL,
    DonGiaSP MONEY NOT NULL CONSTRAINT CTDNH_DonGia CHECK (DonGiaSP >= 0),
    SoLuongSP INT NOT NULL CONSTRAINT CTDNH_SoLuong CHECK (SoLuongSP > 0),
    PRIMARY KEY (MaDNH,MaSP),
	FOREIGN KEY (MaDNH) REFERENCES DONNHAPHANG(MaDNH),
	FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)
);

CREATE TABLE DONGIAOHANG 
(
    MaDGH INT PRIMARY KEY IDENTITY(1,1),
    NgayGiaoDGH DATE NOT NULL DEFAULT GETDATE(),
    MaDNH INT NOT NULL,
    MaNV CHAR(5) NOT NULL,
	FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
	FOREIGN KEY (MaDGH) REFERENCES DONNHAPHANG(MaDNH)
);

CREATE TABLE CT_DONGIAOHANG 
(
    MaDGH INT NOT NULL,
    MaSP CHAR(5) NOT NULL,
    DonGiaDGH MONEY NOT NULL CONSTRAINT positive_ctdgh_dongia CHECK (DonGiaDGH >= 0),
    SoLuongDGH INT DEFAULT 1 CONSTRAINT positive_ctdgh_soluong CHECK (SoLuongDGH > 0),
	PRIMARY KEY (MaDGH,MaSP),
	FOREIGN KEY (MaDGH) REFERENCES DONGIAOHANG(MaDGH),
	FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)
);

CREATE TABLE THANH_TOAN_ATM 
(
	MaHD CHAR(10) PRIMARY KEY,
	STK CHAR(10) NOT NULL,
	ThoiGianTT_ATM DATE NOT NULL DEFAULT GETDATE(),
	FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD),
);

CREATE TABLE THANH_TOAN_TIEN_MAT 
(
	MaHD CHAR(10) PRIMARY KEY,
	ThoiGianTT_TM DATE NOT NULL,
	SoTienTraLai MONEY NOT NULL DEFAULT 0 CONSTRAINT CHK_SoTienTraLai CHECK (SoTienTraLai >= 0),
	FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD)
);

CREATE TABLE GIO_HANG 
(
	MaKH CHAR(10) NOT NULL,
	MaSP CHAR(5) NOT NULL,
	SoLuongGioHang INT NOT NULL DEFAULT 1 CHECK (SoLuongGioHang > 0),
	PRIMARY KEY (MaKH, MaSP),
	FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),
	FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)
);
/*
drop table LUONG
drop table DIEMDANH
drop table LICH_SU_GIA
drop table CT_HOADON
drop table CT_DONGIAOHANG
drop table CT_DONNHAPHANG
drop table SANPHAM
drop table NHACUNGCAP
drop table HOADON
drop table KHACHHANG
drop table NHANVIEN
drop table DONNHAPHANG
drop table TAIKHOAN*/
